### ISSUE TITLE
No build folder 

### ISSUE THREAD

**Issue by didi3r** [sroze/ngInfiniteScroll#330]
Where is the build folder or how can I generate it?

**Comment by graingert** [comment]
The build folder can be generated by running `npm prepublish`

But you probably want to do `npm install --save ng-infinite-scroll`

**Comment by deividfortuna** [comment]
I am having the same issue. Using bower. The tag 1.3.1 is broken. I think you pretend remove the build you must release a minor or major version.

**Comment by graingert** [comment]
@deividfortuna Apologies for the down-time of your builds, but bower support was dropped quite a while ago (I wasn't pretending), and you should be aiming to upgrade to npm. However, a bower version is now available at https://github.com/ng-infinite-scroll/ng-infinite-scroll-bower it's auto-built via travis. With thanks to @vikalpj

**Comment by graingert** [comment]
Your builds broke as a result of configuring the auto bower builds, requiring a new tag to be released.

Because bower is not supported, the semver tags relate to npm versions, not bower. Because there were no changes to the npm code only a minor version bump was required.

The npm version is tested and verified to work. YMMV on the bower builds.
