### ISSUE TITLE
Version 1.3.1 broke my build

### ISSUE THREAD

**Issue by moneytree-doug** [sroze/ngInfiniteScroll#332]
I had to omit the caret and lock the version to ``#1.3.0`` in bower. I don't know why it broke, but it did.

**Comment by spacem** [comment]
Try changing your bower.json to use the new name:
ng-infinite-scroll-npm-is-better-than-bower

- not sure why there is so much hate going around for bower haha

**Comment by kapke** [comment]
I've had the same issue. It looks that someone made a mistake during publishing (there's no `build` directory in `1.3.1`). It also seems that there was a complete rewrite from Coffeescript into ES2015 between version `1.3.1` and `1.3.0`. So everything breaks down into not following semantic versioning rules.

**Comment by moneytree-doug** [comment]
@kapke Agreed. This should have been a 1.X.0 change

**Comment by graingert** [comment]
@moneytree-doug @kapke @spacem Apologies for the down-time of your builds, but bower support was dropped quite a while ago (I wasn't pretending), and you should be aiming to upgrade to npm. However, a bower version is now available at https://github.com/ng-infinite-scroll/ng-infinite-scroll-bower it's auto-built via travis. With thanks to @vikalpj

Your builds broke as a result of configuring these auto bower builds, requiring a new tag to be released.

Because bower is not supported, the semver tags relate to npm versions, not bower. Because there were no changes to the npm code only a minor version bump was required.

The npm version is tested and verified to work. YMMV on the bower builds.

**Comment by graingert** [comment]
> It also seems that there was a complete rewrite from Coffeescript into ES2015 between version 1.3.1 and 1.3.0. So everything comes into not following semantic versioning rules.

There are no actual code changes between 1.3.0 and 1.3.1. The code was not "(rewritten) from Coffeescript into ES2015" it was directly compiled from CoffeeScript to ES2016 without changing functionality.

The built files, are of course included in the npm package.

**Comment by graingert** [comment]
@moneytree-doug please check if there are existing bugs before starting a new one.
