### ISSUE TITLE
Error… dynamic height?

### ISSUE THREAD

**Issue by fidoboy** [sroze/ngInfiniteScroll#44]
Hello i'm getting this error:

error: 'undefined' is not a function (evaluating 'n.height()') 

when using infinite scroll. I'm using a ul list and repeated items are li elements. May be that the source of this problem is the height of each li item? currently there is not a fixed height for each item, so may be infinite scroll has some problems with this…

**Comment by helzgate** [comment]
Heads up to all those out there reading this post and having the urge to put jquery before angular.  This caused me hours and hours worth of troubleshooting because i ended up having ng-click fire multiple times not knowing why (and this isn't always apparent in your app).  I finally tracked it down to the fact that i was loading jquery before angular.  Problem was, if tried loading jquery after angular ng-infinate-scroll would quit working.  I ended up using the latest non-stable release of ng-infinate-scroll and now i can load jquery after angular and now my ng-click's work properly and all is well.

**Comment by jbarros35** [comment]
having same problem here.
{
  "name": "business-casual",
  "description": "A starter project for AngularJS with bootstrap, Angular and Require.js",
  "version": "0.3.0",
  "homepage": "https://github.com/jbarros35/angular/business-casual",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.4.x",
    "angular-route": "1.4.x",
    "angular-loader": "1.4.x",
    "angular-mocks": "~1.4.x",
    "html5-boilerplate": "~4.3.0",
    "requirejs-text": "2.0.x",
    "requirejs": "2.1.x",
    "bootstrap": "~3.3.4",
    "angular-resource": "~1.4.0",
    "angular-bootstrap": "~0.13.0",
    "ngstorage": "~0.3.5",
    "crypto-js": "~3.1.5",
    "ngDialog": "~0.4.0",
    "ngInfiniteScroll": "1.0.0"
  },
  "resolutions": {
    "angular": "1.4.1"
  }

**Comment by roman-ku** [comment]
@netputer 

Thanks! That did the trick!
